"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from __future__ import absolute_import
from setuptools import setup, Extension
from pybind11.setup_helpers import Pybind11Extension, build_ext

'''
from sys import setrecursionlimit
setrecursionlimit(10000)
APP = ['micc/cli.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
'''

ext_modules = [
    Pybind11Extension(
        "_micc_dfs",
        ["micc/dfs_module.cpp"],
    ),
]

setup(name='MICC',
      version='0.1.3',
      author='Matt Morse, Paul Glenn',
      author_email='mjmorse@buffalo.edu, paulglen@berkeley.edu',
      packages=['micc', 'micc.tests'],
      url='http://micc.github.io',
      download_url='https://github.com/micc/micc',
      license='LICENSE',
      description='An implementation of the Birman-Margalit-Menasco Theorem, to be used in a experimental, exploratory manner.',
      long_description=open('README.rst').read(),
      ext_modules=ext_modules,
      cmdclass={"build_ext": build_ext},
      install_requires=[
          "numpy",
          "six",
          "pybind11"
      ],
      tests_require=["pytest"],
      test_suite="pytest")
